GeoNode/django-osgeo-importer

Vagrantfile
scripts/downloads.sh
scripts/install.sh

Ref: https://github.com/ProminentEdge/django-osgeo-importer/issues/13

test data is now public; remove dependency on AWS key env vars

---

setup.py

Reference previous dupe: https://github.com/ProminentEdge/django-osgeo-importer/pull/20

let tastypie version be flexible to avoid conflicts

---

osgeo_importer/handlers/__init__.py
osgeo_importer/handlers/geonode/__init__.py
osgeo_importer/handlers/geoserver/__init__.py
osgeo_importer/inspectors.py
osgeo_importer/utils.py
osgeo_importer_prj/settings.py

Instead of hardcoding the database name 'datastore', allow the name to be specified in settings along with the rest of the db config.
Ref: https://github.com/ProminentEdge/django-osgeo-importer/issues/12

Get database name from settings instead of hardcoding

---

osgeo_importer/tests.py
scripts/build_gdal.sh
scripts/install.sh

Adds support for additional file formats to the vagrant build for Geopackage and WFS.

add geopackage and wfs support to gdal

---

setup.py

Without this I was finding that a `pip install` of django-osgeo-importer was yielding a version which
didn't quite work (Django tracebacks due to django-osgeo-importer templates unexpectedly missing, and 404s and frontend issues due to static files not being served).
To test for this kind of thing, you may have to do a `pip install` without `-e`, or it will implicitly pick up a bunch of files in the directory that `pip install -e` is pointed to, but which are not collected via the MANIFEST mechanism used by clean pip installs.

make package installs include essential templates and static files

---

osgeo_importer/tests.py

This assertion was always succeeding because the value of the Python expression `('xsd:dateTime' or ...)` is always `'xsd:dateTime'`, which is truthy, so that `assertTrue` passes regardless of what is happening. One could guess this wouldn't be intended, but the comment `make sure we have at least one dateTime attribute` makes the original intention very clear.
To complicate matters, it looks like there were several tests which should have been failing before, and now are failing because this assertion has been fixed, which will cause any future PRs to fail the tests. It would help me if someone more familiar with the date requirement could fix these test failures so that the test suite can be used to validate future PRs that are in the works.
Please don't hesitate to tell me if there are …

fix assertion against layer attributes

---

osgeo_importer/tests.py

Per @sarasafavi on #37, several of the test datasets do not contain any dateTime or date attributes, and this is a legacy requirement anyway. In light of this, it appears that the test failures this assertion is causing are spurious, so that it would be better to remove it in order to allow future PRs to be tested accurately on the CI

remove unused assertion

---

osgeo_importer/static/osgeo_importer/css/importer.css
osgeo_importer/static/osgeo_importer/partials/uploadWizard.html

To improve the user experience, I changed some copy for consistency/accuracy.
I also refactored the CSS so that it was more consistently styled with appropriate semicolons, etc.
The other change here is to update colors for the stepper in the wizard so that it's not using red or green, colors often associated with success and failure (which may be confusing to users, since they're in the middle of a multi-step process).

Ux fixes for upload wizard

---

scripts/before_script.sh

this was leading to an error during vagrant provision:
`/tmp/vagrant-shell: line 14: [-f: command not found`

add spaces around shell operator -f and its argument

---

osgeo_importer/utils.py

Right now, every user of this django app must have `numpy` installed. But `numpy` is currently only being used in `utils.timeparse`. `utils.timeparse` is only being used by `BigDateOGRFieldConverter`, which is only used by `handlers.BigDateFieldConverterHandler`. 
The docstring for that class states that using it requires a special build of GeoTools. Unless that special build is a requirement of django-osgeo-importer, any installation without it will already be unable to use `BigDateFieldConverterHandler`, which is the only user of `numpy`.
Deferring this import allows individual installations to either use or not use numpy depending on whether they also have the right GeoTools setup and intend to use `BigDateOGRFieldConverter`.

don't require numpy to run, unless using timeparse

---

osgeo_importer/importers.py
osgeo_importer/inspectors.py
osgeo_importer/tests.py

Previously discussed at https://github.com/boundlessgeo/django-osgeo-importer/pull/39
To summarize, this is to allow the use of raster formats like NITF and not just GeoTiff.

Additional raster support

---

README.md

I think we should commit to designate certain formats as officially supported, and by implication other formats as not supported (which doesn't mean they won't work, just that we reserve the right to break them if we are ever forced to).
Officially supported formats are default-whitelisted formats which we have tests for and which are in the default GDAL build, or which we can't find any realistic GDAL packages which don't support them (e.g. ubuntu, centos).
also tracked in Boundless JIRA as
https://issues.boundlessgeo.com:8443/browse/NODE-494

document some formats as officially supported

---

osgeo_importer/tests/tests_original.py

Some test assertions were .assertTrue() that should have been .assertEqual() to check a web request status code.  While I'm at it; add a check for the number of layers that should have been configured here.

Fix some assertion mistakes & add a layer count assertion to UploaderTests.test_multi_upload().

---

osgeo_importer/handlers/geoserver/__init__.py
osgeo_importer/tests/handlers/test_geoserver.py
osgeo_importer/tests/helpers.py
osgeo_importer/tests/test_utils.py
scripts/install.sh

First, an update to make builds work again; script install of postgres-9.3-postgis-2.2 -> postgres-9.3-postgis-2.3.  Didn't dig into what had changed to require it, but the problem is in master as well so it's not related to code but to unpinned versions of packages installed.
Code changes:
Previously if the workspace hadn't been manually created raster layers were accidentally saved to the default workspace but the UI still tried to serve them from workspace "geonode".
Additionally made some needed but unrelated changes to tests:
Test import_all_layers prepped for testing more than one file.
@works_with_geoserver updated to clean up in the case of a test error.

Ensure workspace exists before store creation.

---

osgeo_importer_prj/settings.py

GeoNode's settings file has eliminated it, no reason for us to keep it around.

Replaced deprecated TEMPLATE_DIRS with TEMPLATES in settings.

---

osgeo_importer/handlers/geonode/publish_handler.py
osgeo_importer/handlers/geoserver/__init__.py
osgeo_importer/handlers/mapproxy/conf_geopackage.py
osgeo_importer/handlers/mapproxy/publish_handler.py
osgeo_importer/importers.py
osgeo_importer/inspectors.py
osgeo_importer/migrations/0009_mapproxycacheconfig.py
osgeo_importer/models.py
osgeo_importer/tests/handlers/geonode/test_publish_handler.py
osgeo_importer/tests/handlers/mapproxy/test_conf_geopackage.py
osgeo_importer/tests/handlers/mapproxy/test_publish_handler.py
osgeo_importer/tests/handlers/test_geoserver.py
osgeo_importer/tests/tests_original.py
osgeo_importer_prj/settings.py
scripts/install.sh

If the mapproxy import handler and settings variables are uncommented these changes will stash a copy of the gpkg file and update mapproxy's configuration to serve the tiles it contains.  These updates won't cause any changes to other functionality so mapproxy-ignorant code can remain so.
These updates don't configure things so GeoNode knows where to look for those tiles; that is still to come.

Configure mapproxy to serve gpkg files containing tiles on import.

---

osgeo_importer/handlers/geonode/publish_handler.py
osgeo_importer/handlers/mapproxy/publish_handler.py
osgeo_importer/tests/handlers/mapproxy/test_publish_handler.py
osgeo_importer_prj/settings.py

The title says it all, when gpkg tile layers are imported a base link to access them via mapproxy will be stored in geonode's Link model.
I expect a corresponding change here: https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L685
would be the best way to make this available to views/templates, but will wait on that until Jeff/Mila confirm how they want to access the links.

Add TMS Link in mapproxy publish handler.

---

docs/developer_notes.rst
docs/mapproxy_config.rst
requirements.dev.txt
scripts/downloads.sh
scripts/install.sh

Having a development requirements package helps improve visibility of which packages & versions tests use.
Makes set up of common development arrangements not using vagrant (docker, virtualenv) easier.

Move development pip dependency installation from scripts to requirements.dev.txt.

---

scripts/docker-dev/docker-compose.yaml
scripts/docker-dev/geoserver/Dockerfile
scripts/docker-dev/geoserver/startup_extra.sh
scripts/docker-dev/postgres-postgis/Dockerfile
scripts/docker-dev/postgres-postgis/init-user-db.sh

Simple docker-compose.yaml & two Dockerfiles to run postgres and geoserver instances on standard ports.
Makes it easy and quick to reset these services and develop / test without configuring or polluting instances of these services on your development machine.

Docker images for postgres & geoserver with docker-compose for developing from a virtualenv.

---

osgeo_importer/migrations/0010_auto_20170109_1401.py
osgeo_importer/models.py
osgeo_importer/tests/test_views.py

https://github.com/GeoNode/django-osgeo-importer/issues/80

Increase allowed length of UploadedData.name to accomodate longer filenames.

---

osgeo_importer/inspectors.py
osgeo_importer/migrations/0011_uploadlayer_layer_type.py
osgeo_importer/models.py
osgeo_importer/tests/test_utils.py
osgeo_importer/tests/tests_original.py
osgeo_importer/utils.py
scripts/docker-dev/docker-compose.yaml

Mostly updates in utils to ensure that unique layer names are generated and stored in UploadLayers which are used as default names when layer name is not configured manually, such as for bulk import operations.
Some related changes to ensure layer_type is available in import_all_layers()
Unrelated minor change in docker-compose.yaml to match database name to name used in default settings file.

Give human-readable and unique names to imported layers.

---

README.md
osgeo_importer/importers.py
osgeo_importer/tests/tests_original.py
osgeo_importer/utils.py
osgeo_importer_prj/settings.py
scripts/epsg_extra
scripts/install.sh

Adds a utility for converting WKT strings to EPSG codes, and utilizes it in the importer if AutoIdentifyEPSG() fails to find a valid EPSG code for the dataset.  Also adds an extra_epsg file where we can add additional EPSG codes and their matching projections if they aren’t included in the default installation.  The extra_epsg file is copied to the /usr/share/proj directory where all EPSG code files are during the install process.

Add WKT to EPSG Utility to Find EPSG Codes

---

osgeo_importer/tests/tests_original.py
osgeo_importer/utils.py

Set the UploadLayer name to the unique layername rather than absolute path provided by upfile.file.name, since the file.name could easilt go over 64 characters

Set the UploadLayer name to the unique layername

---

osgeo_importer/api.py
osgeo_importer/importers.py
osgeo_importer/inspectors.py
osgeo_importer/migrations/0012_uploadlayer_internal_layer_name.py
osgeo_importer/models.py
osgeo_importer/tests/test_importers.py
osgeo_importer/tests/tests_original.py
osgeo_importer/utils.py
osgeo_importer/validators.py
osgeo_importer/views.py

Needed some refactoring to require the id of an UploadLayer associated with a layer being imported to be included in the configs.
Existing tests updated to call configure_upload() which is where unique layer names are assigned before any import attempt.

Update PostGIS table name creation to use unique layernames provided by configure_upload().

---

osgeo_importer/forms.py
osgeo_importer/tests/test_validators.py
osgeo_importer/validators.py

This PR is a proposal that we only process valid extensions in our list, rather than trying to figure out all of the different types of files that users may have in their zip files and exclude those.  I expect that users will be fairly unpredictable in what they'll include in their zip files outside of the required file types for a layer, and that this will be easier than figuring out all of those file types they may include.

Only process valid extensions

---

osgeo_importer/templates/osgeo_importer/bulk_import.html
osgeo_importer_prj/settings.py
requirements.txt

It adds the importer client as a django app. 
use SITEURL for the server settings
Importer Client has version 0.0.4 with a few improvements. The progress can be found here: 
https://github.com/terranodo/importer-client

Add importer-client as pypi package

---

osgeo_importer/handlers/__init__.py
osgeo_importer/handlers/geoserver/__init__.py
osgeo_importer/importers.py

This fixes two isues:
- Currently all the data is ingested into the public schema, This makes it possible to store the data in a different schema
- The Geoservers may be created in an existing workspace that has a different nampsapce that the expected namespace, which will end up breaking the store, or more precisely layers add from the store will not work. This removes the namespace from the store (will be inherited on creation)

Postgres Schema

---

.gitignore
osgeo_importer_prj/settings.py
requirements.dev.txt
requirements.txt

Update the Geonode requirements to use PyPi and give a range of versions allowed that I’ve tested and verified as passing the tests.  Also moved the uploaded directory to within the project structure instead of inside of Geonode due to permissions issues with the old upload directory when installing Geonode via PyPi.

Update GeoNode Requirements

---

docker-compose.yml
osgeo_importer/importers.py
osgeo_importer/tests/tests_original.py
osgeo_importer/utils.py

This PR adds support for ESRI projections that previously failed in Importer.  If we can't automatically find an EPSG code for the layer, we reproject it into 4326 by creating a new layer and projecting all of the features to that new projection, and then we import this new layer instead.

Esri projection support

---

osgeo_importer/handlers/geonode/publish_handler.py

Ensures that the title the users selects during the import process is properly used.  Currently the title that the user enters during the import process is not being used.

Fixes Title During Import

---

osgeo_importer/handlers/geonode/publish_handler.py

Currently the workspace is in every single URL followed by a colon and then the rest of the layers name.  This just clutters up the URL and from what I can tell is unnecessary.  If anyone knows the reason it needs to be there, feel free to let me know.  But all of the tests are passing locally with this change.

Removes the workspace from the typename, which removes it from the URL.

---

requirements.dev.txt

Bumps geonode to version 2.6.3 to avoid issues with future versions of shapely.

Bump Geonode to 2.6.3

---

osgeo_importer/static/osgeo_importer/importer.js

This updates the deprecated .success and .error functions to the stable .then response for forward compatibility with angular 1.4, 1.6, etc.
Some of the http.get requests aren't being used from what I can tell, but I updated their expected responses anyway.

Update deprecated .success function and expected response

---

osgeo_importer/importers.py

Reprojection code is trying to save data using the layer id rather than the upload id to create the path to save.

fix reprojection to use correct directory

---

osgeo_importer/__init__.py
osgeo_importer/handlers/geoserver/__init__.py
osgeo_importer/importers.py
osgeo_importer/inspectors.py
osgeo_importer/utils.py

- Fix missing first feature on vector reprojection
- Change ```PG_USE_COPY``` to make it possible to ingest larger datasets
- Change the geometery auto promotion to only be invoked if there are two types/classes of geometries in a shapefile 
- Make sure raster layers get their name based on the importer layer name. 
- Use external raster when creating a geoserver coverage store, instead of uploading the raster on store creation

Raster/Vector Fixes

---

osgeo_importer/__init__.py
osgeo_importer/handlers/geoserver/__init__.py
osgeo_importer/importers.py

This fixes CSV ingest into postgers - currently OGR appends a fake newline to each feature when ingesting CSV into postgres when using COPY.
As a workaround, this uses INSERT for CSV and COPY for all other formats.
Error returned by OGR:
```
ERROR 1: COPY statement failed.
ERROR:  extra data after last expected column
CONTEXT:  COPY testme2222, line 1: "\N  9003    2001-02-02                      30      30                      POINT (-93.676963 42.011123)"
```

Don't use COPY when ingesting CSV

---

docker-compose.yml
osgeo_importer/__init__.py
osgeo_importer/inspectors.py
osgeo_importer/tests/handlers/test_geoserver.py
osgeo_importer/tests/tests_original.py

This makes some fixes to get all the tests to run. It mounts the base directory into the geoserver docker container to allow those tests to pass. 
This reverts PG_USE_COPY to no. This is not as fast, but right now there are some tests that fail when using copy.
This comments out the test for arcgis rest services as there is no current UI endpoint to access this capability anyway. The test fails as there is no upload directory that gets created right now which would need to be added to be able to leverage this function in the future.

fixes to get tests to run

---

osgeo_importer/admin.py
osgeo_importer/handlers/geoserver/__init__.py
osgeo_importer/static/osgeo_importer/css/importer.css
osgeo_importer/static/osgeo_importer/partials/uploadWizard.html
osgeo_importer/tasks.py
osgeo_importer/utils.py

1. This PR ports over the process followed by the geonode.uploader with regards to sld association for newly created layers. A new sld will be created for each layer rather than assigning points.sld to each layer. The screen shot below is the result of successfully uploading/importing three different geometry types, each resulting in a sld named after the layer.
2. This PR also allows .sld files to be included in the layer configuration options. If a user uploads a file which include a .sld, this change will enable the import wizard to display a selector of the available styles associated with the upload so that the user can choose which .sld to apply as the default style.
The following screenshot is the result of a successful import of a shapefile with several sld files included in the …

Updates to SLD Handling and Exception Propagation

---

osgeo_importer/__init__.py
osgeo_importer/importers.py

Currently the majority the KML/KMZ get ingested with undefined geometry, or geometry type 0.
This adds the ```KML``` and ```LIBKML``` drivers to the types modified by the ```types get_layer_type``` method.
Complex KML/KMZ (ones with say, a point/multi-point and a polygon/multi-polygon) will now correctly fail to ingest

Ensure KML/KMZ is ingested with valid geometry 

---

osgeo_importer/handlers/geoserver/__init__.py

In some cases ```default_style``` is reporting None even though a default style is actually set.
This assumes that if None is returned, and a user did not upload a style with the layer, then a layer specific default style should be applied

Fix in case default_style is null

---

osgeo_importer/inspectors.py

Instead of using the type ID number associated with the field (field.type), the importer uses the position of the field in the layer ("i").  This PR fixes this.
GetFieldTypeName(int) -> returns a human-readable (i.e. "Integer" or "Real") given a type field type id.
http://www.gdal.org/classOGRFieldDefn.html
Filed Type IDs:
http://www.gdal.org/ogr__core_8h.html#a787194bea637faf12d61643124a7c9fc

use actual field type name

---

osgeo_importer/handlers/geonode/publish_handler.py

geonode 2.7 requires the alternate field to be set for use in building the details_url.

Set the alternate field

---

osgeo_importer/forms.py

The importer had issues with more complex zips;
a) zip files that have data in a directory (i.e. right click on a folder and zip it)
b) zip files created on macs (have __MACOSX/.* files)
c) zip with shapefiles that have .shp.xml metadata files
This handles these situations.

Handle more complex .zip files

---

osgeo_importer/tests/tests_original.py

This adds a simple test case for a complex zip.  
See https://github.com/GeoNode/django-osgeo-importer/pull/204

Add test case for complex zip files

---

osgeo_importer/importers.py
osgeo_importer/utils.py
osgeo_importer/validators.py

This will attempt to set the encoding specified in a cpg file, if one is provided, when ingesting the data.
eg, `ANSI 1252`, `UTF-8`, `cp950` should be set when data is ingested.

Read encoding from cpg file if exist

---

osgeo_importer/handlers/geoserver/__init__.py
osgeo_importer/importers.py

This PR refactors `create_target_dataset` to `get_or_create_target_dataset` to account for the cases when the target dataset exists. In the case where the import task fails after the create dataset step, the user can resubmit the import request to continue processing.

call get_or_create_target_dataset

---

osgeo_importer/utils.py

This PR avoids the fatal error seen below for some .sld files that are included in the upload. The files still upload but importer raises an exception which causes the user to think the process was aborted. Since the files upload, the user is able to exit the error dialog and proceed with creating/importing the layer along with the sld.
Given that this method attempts to describe the layer info and create an UploadLayer instance, it doesn't apply to .sld files so its safe to exclude .sld files from processing.
>>> data = gdal.OpenEx('/scratch/media_root/osgeo_importer_uploads/14/Public_Schools.sld', open_options=[])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
RuntimeError: `/scratch/media_root/osgeo_importer_uploads/14/Public_Schools.sld' not recognized as a …

No need to process the sld file if included.

---

osgeo_importer/utils.py

Invalid chars in the field names can cause the json parser to fail thus halting the upload. In this PR we safely ignore those characters so that the upload succeeds and the import can begin.

Ignore invalid characters

---

osgeo_importer/importers.py
osgeo_importer/inspectors.py

This PR addresses the issue where field names can fail utf-8 decoding. If decoding fails, it ignores the invalid characters and updates the field name prior to creating the field on the target layer.

Make the data writeable

---

requirements.dev.txt

Stick to the latest Django 1.8 compatible version of django-cors-headers.

Fix MiddlewareMixin import error
