GeoNode/django-osgeo-importer

osgeo_importer/importers.py
Crap: missed one. Dang it Travis CI...
Feel free to squash/reword as preferred. Reference: https://github.com/ProminentEdge/django-osgeo-importer/pull/29
=> patch to fc3b991

README.md, osgeo_importer/static/osgeo_importer/package.json, setup.py
Travis CI and coveralls.io will need additional steps on their websites to adjust, I don't think I have access to do those things.
=> Point to geonode repo

osgeo_importer/tests/helpers.py
A pain to track down but fairly straightforward fix.
=> Takes care of database teardown issue during travis tests.

requirements.dev.txt, scripts/downloads.sh
The editable flag changes the location & permissions of the installed geonode package.  This allows write access to directories in the geonode package for upload and sqlite3 db creation.
=> Added editable flag to geonode install to resolve vagrant testing permission errors.

MANIFEST.in, setup.py
reconfigured setup and manifest to package all required files
=> remove hard dependencies via pip install

osgeo_importer/handlers/mapproxy/publish_handler.py, osgeo_importer/importers.py, osgeo_importer/tests/handlers/mapproxy/test_publish_handler.py, osgeo_importer/tests/tests_original.py, osgeo_importer/utils.py, osgeo_importer_prj/settings.py
Addresses Eventkit Redmine issue #16284.
=> Updates to ensure unique layer names with mapproxy-served layers

osgeo_importer/handlers/geonode/__init__.py
Ensure that the permissions are set for layers that are created in addition to layers that are imported.
=> Add Create Layer Permissions

osgeo_importer/handlers/geoserver/__init__.py
Add the authorName and authorEmail information to the Geogig commit upon Import.
=> Add Author Details to Imports Geogig Commit

requirements.dev.txt, requirements.txt
Updates all of our requirements to use a specific version, confirmed as working and passing all tests.  This should stop any future breaking changes from upstream dependencies.
=> Version Tag Requirements

osgeo_importer/geonode_apis.py, osgeo_importer/handlers/geoserver/__init__.py, osgeo_importer/importers.py, osgeo_importer/static/osgeo_importer/importer.js, osgeo_importer/tasks.py, osgeo_importer/tests/handlers/test_geoserver.py
Updating the Geogig handlers with the customizations that we had made to them in the MapStory branch of importer.
=> Update geogig handlers

osgeo_importer/forms.py, osgeo_importer/tests/handlers/test_geoserver.py, osgeo_importer/tests/test_inspectors.py, osgeo_importer/tests/test_validators.py, osgeo_importer/tests/tests_original.py, osgeo_importer/validators.py
New implementation for file validation that can handle nested zips & won't try to process files with extensions added to IGNORE_EXTENSIONS.
=> Added validators.valid_file() with IGNORE_EXTENSIONS feature.

osgeo_importer/static/osgeo_importer/importer.js
This PR sets the default_config when its null or undefined.
=> Fixed bug where default_config was undefined. 

osgeo_importer/api.py, osgeo_importer/handlers/geoserver/__init__.py
Ensure that the request user is properly passed and guard against it being None during import.
=> Pass Request User on Import

osgeo_importer/handlers/geoserver/__init__.py
Add the authorName and authorEmail information to the Geogig commit upon Import.
=> Add authorName and authorEmail

osgeo_importer/inspectors.py
Basic connection failure logging to help diagnose installation problems.
=> Add logging & exception message to NoDataSourceFound errors.

osgeo_importer/handlers/__init__.py, osgeo_importer/handlers/geoserver/__init__.py, osgeo_importer/importers.py, osgeo_importer/utils.py
This fixes an issue with https://github.com/GeoNode/django-osgeo-importer/pull/150 where the schema wasn't passed to the geogig data ingest.
Adds automatic geogig index creation for geogig >= 1.1
=> Geogig index creation and Postgres fix

osgeo_importer/handlers/geonode/publish_handler.py
In certain cases that I've been testing on MapStory, self does not always contain the store that we're expecting.  For these cases I've added a fallback to check the layer_config for the store name.
=> Add Additional Checks to find Store Name

osgeo_importer/static/osgeo_importer/importer.js
Ensure that the appendTo configuration gets properly added to the configuration and make sure it doesn’t get overwritten.
=> Ensure Append Config Doesn't Get Overwritten

osgeo_importer/forms.py
This PR changes the way we check for the extension when comparing it to VALID_EXTENSIONS and handles all cases including where an extension could have multiple dots in it.
=> Update extension check

osgeo_importer_prj/settings.py
Update OGC_SERVER settings to use Geonode defaults with a few tweaks for Docker.
=> Update OGC Settings Docker

osgeo_importer/handlers/geonode/publish_handler.py
This change allows the abstract to be persisted with the layer during creation.
=> Populates Abstract if available in the config

osgeo_importer/handlers/geonode/publish_handler.py, osgeo_importer/static/osgeo_importer/css/importer.css
Populates the category if available in the config.
Example Layer Config:
=> Adds support for the GeoNode TopicCategory

osgeo_importer/handlers/geoserver/__init__.py, requirements.dev.txt
Handles a condition where the get_store command returns None instead of an exception.
=> Handle Store is None Condition

osgeo_importer/importers.py, osgeo_importer/tests/tests_original.py
Ensure that all fields are checked for proper encoding and valid data before trying to create a feature, put UTF8 test back in.
=> Check for Valid Data and Encoding

osgeo_importer/__init__.py, osgeo_importer/importers.py
Same as https://github.com/GeoNode/django-osgeo-importer/pull/193
=> Ensure KML/KMZ is ingested with valid geometry - Angular branch

osgeo_importer/forms.py, osgeo_importer/tests/tests_original.py, osgeo_importer/utils.py, osgeo_importer/views.py, osgeo_importer_prj/settings.py
Creates a quota for lifetime uploads for a user. Bex-452. Quota is measured in kilobytes.
=> Upload quota BEX 452

osgeo_importer/handlers/geonode/publish_handler.py
Reverts GeoNode/django-osgeo-importer#202
=> Revert "Set the alternate field"

osgeo_importer/importers.py
Copy seems to fail in several places that using inserts work. In particular with encoding issues. This attempts copy first for speed, but will then fallback to using inserts if the copy does not work.
=> fallback to inserts if copy doesnt work

osgeo_importer/inspectors.py
Fixes an issue in append where the workspace is no longer in the layer name.
=> Fixes Append Workspace Name

osgeo_importer/handlers/geoserver/__init__.py
For consistency in this module, lets make the style global.
=> Make style global

osgeo_importer/handlers/geoserver/__init__.py
This PR addresses the bug where the layer import fails if Geoserver is unable to read the sld. Rather than fail the entire import, the proposed refactor catches the specific UploadError, gracefully cleans up, and proceeds with the layer import.
[Ferry_Routes.zip](https://github.com/GeoNode/django-osgeo-importer/files/2481043/Ferry_Routes.1.zip)
=> Layer import fails if sld is unreadable

osgeo_importer/api.py, osgeo_importer/handlers/geoserver/__init__.py, osgeo_importer/importers.py, osgeo_importer/inspectors.py, osgeo_importer/tests/tests_original.py, osgeo_importer/utils.py, osgeo_importer_prj/settings.py
* Safely avoid invalid characters
* Layer import fails if sld is unreadable
=> Includes bug fixes from 1.6 branch

osgeo_importer/handlers/geoserver/__init__.py
@davisc could you take a look?
=> Fallback for newer version of gsconfig
